version: "3.9"
services:
  osrm:
    container_name: osrm
    image: osrm/osrm-backend:latest
    restart: unless-stopped
    ports:
        - "5000:5000"
    volumes:
        - ./data:/data
    command: "osrm-routed --algorithm mld /data/indiana-latest.osrm"